### ISSUE TITLE
Grey screen after connecting, then the game crashes.

### ISSUE THREAD

**Issue by EliasFleckenstein03** [HimbeerserverDE/multiserver#21]
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff6e78859 in __GI_abort () at abort.c:79
#2  0x00007ffff724d951 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff725947c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff72594e7 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff7259799 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff725077f in std::__throw_system_error(int) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x0000555555c33def in std::mutex::lock (this=0x555556ace400) at /usr/include/c++/9/bits/std_mutex.h:104
#8  0x0000555555c39b6f in std::unique_lock<std::mutex>::lock (this=0x7fffffffcbb0) at /usr/include/c++/9/bits/unique_lock.h:141
#9  0x0000555555c36791 in std::unique_lock<std::mutex>::unique_lock (this=0x7fffffffcbb0, __m=...) at /usr/include/c++/9/bits/unique_lock.h:71
#10 0x00005555560a65ff in Environment::getDayNightRatio (this=0x555556ace3b8) at /home/fleckenstein/minetest/src/environment.cpp:47
#11 0x0000555555c66c6d in ClientMap::renderMap (this=0x555556accf60, driver=0x555556941010, pass=8) at /home/fleckenstein/minetest/src/client/clientmap.cpp:282
#12 0x0000555555c6c2bb in ClientMap::render (this=0x555556accf60) at /home/fleckenstein/minetest/src/client/clientmap.h:112
#13 0x00007ffff7ce3b19 in irr::scene::CSceneManager::drawAll() () from /lib/x86_64-linux-gnu/libIrrlicht.so.1.8
#14 0x0000555555dce364 in GUIEngine::cloudPreProcess (this=0x7fffffffd230) at /home/fleckenstein/minetest/src/gui/guiEngine.cpp:370
#15 0x0000555555dcdae2 in GUIEngine::run (this=0x7fffffffd230) at /home/fleckenstein/minetest/src/gui/guiEngine.cpp:287
#16 0x0000555555dccf04 in GUIEngine::GUIEngine (this=0x7fffffffd230, joystick=0x555556a12c48, parent=0x55556ab8b690, menumgr=0x5555565a8780 <g_menumgr>, data=0x7fffffffd510, kill=@0x5555565dbec0: false) at /home/fleckenstein/minetest/src/gui/guiEngine.cpp:196
#17 0x0000555555c5b94f in ClientLauncher::main_menu (this=0x7fffffffdaa0, menudata=0x7fffffffd510) at /home/fleckenstein/minetest/src/client/clientlauncher.cpp:566
#18 0x0000555555c5aae3 in ClientLauncher::launch_game (this=0x7fffffffdaa0, error_message="", reconnect_requested=false, start_data=..., cmd_args=...) at /home/fleckenstein/minetest/src/client/clientlauncher.cpp:433
#19 0x0000555555c59489 in ClientLauncher::run (this=0x7fffffffdaa0, start_data=..., cmd_args=...) at /home/fleckenstein/minetest/src/client/clientlauncher.cpp:239
#20 0x00005555560e7188 in main (argc=1, argv=0x7fffffffdef8) at /home/fleckenstein/minetest/src/main.cpp:229
```

**Comment by EliasFleckenstein03** [comment]
![screenshot_20210220_185234](https://user-images.githubusercontent.com/54945686/108604039-bcdaf480-73ab-11eb-9f90-52b535f0b54d.png)

**Comment by EliasFleckenstein03** [comment]
This happens almost every time now.

**Comment by EliasFleckenstein03** [comment]
And the player seems to still be online on the actual minetest server.

**Comment by EliasFleckenstein03** [comment]
Seems fixed
