### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by EliasFleckenstein03** [HimbeerserverDE/multiserver#30]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5e4400]

goroutine 94927 [running]:
main.(*NodeDef).ID(...)
        /home/elidragonmt/go/pkg/mod/github.com/!himbeerserver!d!e/multiserver@v1.7.0/nodedef.go:27
main.processAddnode(0xc00281e000, 0xc000048fa0, 0xc000048ea4)
        /home/elidragonmt/go/pkg/mod/github.com/!himbeerserver!d!e/multiserver@v1.7.0/blockdata.go:68 +0xc0
main.processPktCommand(0xc00281e500, 0xc00281e000, 0xc000048fa0, 0x1f5)
        /home/elidragonmt/go/pkg/mod/github.com/!himbeerserver!d!e/multiserver@v1.7.0/command.go:156 +0x2c5
main.Proxy(0xc00281e500, 0xc00281e000)
        /home/elidragonmt/go/pkg/mod/github.com/!himbeerserver!d!e/multiserver@v1.7.0/proxy.go:66 +0x3b0
created by main.(*Peer).Redirect
        /home/elidragonmt/go/pkg/mod/github.com/!himbeerserver!d!e/multiserver@v1.7.0/redirect.go:172 +0xa77
```

**Comment by EliasFleckenstein03** [comment]
This happens every time I try to use bonemeal on the creative server

**Comment by EliasFleckenstein03** [comment]
And when the server restarts after the crash, it always gets stuck at "Fetching media"

**Comment by HimbeerserverDE** [comment]
This is caused by inexistent node definitions. I will fix this when I do NodeDef refetching and merge RPC and media reconnect into one thing.
