### ISSUE TITLE
Another crash

### ISSUE THREAD

**Issue by EliasFleckenstein03** [HimbeerserverDE/multiserver#37]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x60e5eb]

goroutine 2960 [running]:
main.(*ToolCapabs).GroupCaps(...)
        /home/elidragonmt/go/pkg/mod/github.com/!himbeerserver!d!e/multiserver@v1.8.1/itemdef.go:86
main.(*ToolCapabs).SerializeJSON(0x0, 0xc001cf1da0, 0xc000016a17, 0x5, 0x91e680)
        /home/elidragonmt/go/pkg/mod/github.com/!himbeerserver!d!e/multiserver@v1.8.1/itemdef.go:146 +0x4b
main.(*Peer).UpdateHandCapabs(0xc002586dc0, 0x78b320, 0xc004b3eb10)
        /home/elidragonmt/go/pkg/mod/github.com/!himbeerserver!d!e/multiserver@v1.8.1/hand.go:24 +0x146
main.processPktCommand(0xc002586f00, 0xc002586dc0, 0xc0047d7fa0, 0x400)
        /home/elidragonmt/go/pkg/mod/github.com/!himbeerserver!d!e/multiserver@v1.8.1/command.go:196 +0x1a5
main.Proxy(0xc002586f00, 0xc002586dc0)
        /home/elidragonmt/go/pkg/mod/github.com/!himbeerserver!d!e/multiserver@v1.8.1/proxy.go:66 +0x3b0
created by main.main.func1
        /home/elidragonmt/go/pkg/mod/github.com/!himbeerserver!d!e/multiserver@v1.8.1/multiserver.go:89 +0xd4

```

Afterwards the hand is an unknown item

**Comment by HimbeerserverDE** [comment]
This happens if the hand capabilities for a server is missing. Fixing the crash doesn't fix: the tool capabilities of the hand are empty if the hand list is modified by the minetest server you are on until media is redownloaded.
